version: "3.9"

services:
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always
volumes:
  data:
